version: "3"
services:
    postgres_db:
        image: 'postgres:latest'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    api:
        depends_on: 
                - postgres_db
        image: jayanthid/simple-blog-api:V1
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - POSTPGRES_HOST=postgres_db
            - SIMPLEBLOGAPI_PORT=5432
            - POSTGRES_USER=postgres
            - PGPASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api